### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by bernaferrari** [chuabingquan/helm#1]
Really awesome project. As per [Hacker News discussion](https://news.ycombinator.com/item?id=22618675), Could you please include a LICENSE file? I would personally recommend MIT or Apache2.

**Comment by chuabingquan** [comment]
@bernaferrari thanks for the compliment! The hackathon we made this project for owns our IP. I'm currently clarifying with the organisers to see if we are allowed to add a permissive license for our project. Will update here again when I get news from them.

**Comment by chuabingquan** [comment]
@bernaferrari the hackathon organisers own the rights to the IP. I don’t think it’ll be a good idea for me to license this project, am truly sorry about it.
