### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by ppamorim** [chuabingquan/helm#2]
I tried to follow all the steps in your tutorial and I am only getting a white screen when running the app on a real iPhone X. Any suggestion?

**Comment by chuabingquan** [comment]
@ppamorim that's weird, did the console print out any errors?

**Comment by ppamorim** [comment]
@chuabingquan 
<img width="596" alt="Screenshot 2020-03-20 at 15 47 06" src="https://user-images.githubusercontent.com/5521682/77180610-19f66800-6ac2-11ea-8303-421f5559ee24.png">

**Comment by chuabingquan** [comment]
@ppamorim can you run `flutter doctor` and post your output here? Also can you go to the root directory of the project and execute `flutter run` from there? I think Flutter would fetch some dependencies in the process.

**Comment by ppamorim** [comment]
<img width="618" alt="Screenshot 2020-03-20 at 15 15 38" src="https://user-images.githubusercontent.com/5521682/77181192-e0722c80-6ac2-11ea-978f-615b0560cdfe.png">

**Comment by ppamorim** [comment]
<img width="614" alt="Screenshot 2020-03-20 at 15 54 22" src="https://user-images.githubusercontent.com/5521682/77181374-1dd6ba00-6ac3-11ea-8863-852081841a88.png">

**Comment by chuabingquan** [comment]
@ppamorim can you try to run `flutter build ios`, then `flutter run` after?

**Comment by chuabingquan** [comment]
@ppamorim please try to follow [this](https://github.com/flutter/flutter/issues/24887#issuecomment-526857755)

**Comment by ppamorim** [comment]
@chuabingquan Still the same, tried everything :(

**Comment by chuabingquan** [comment]
@ppamorim please give me some time to reproduce this issue, I'll get back to you asap

**Comment by ppamorim** [comment]
@chuabingquan That's ok, don't worry.

**Comment by chuabingquan** [comment]
@ppamorim I was able to reproduce the issue on a fresh clone of the project. Just delete the `ios` and `android` directories and run `flutter create .` to regenerate a fresh project. Run `flutter pub run flutter_launcher_icons:main` after to set the application's icon, then that should be all. Let me know if that works for you!

**Comment by ppamorim** [comment]
@chuabingquan Thank you, it's working now.
