### ISSUE TITLE
i18n?

### ISSUE THREAD

**Issue by tiaod** [chuabingquan/helm#3]
A very impressive project, it would be great if it could support multiple languages

**Comment by chuabingquan** [comment]
@tiaod thanks for your interest in this project! I will get down to internationalisation once I've cleared some issues with the licensing. Will update this thread when licensing is resolved!

**Comment by chuabingquan** [comment]
@tiaod the hackathon organisers own the IP for this project. Therefore, I won’t be continuing it as the project’s fate is in a state of limbo. Am truly sorry about it. 😔
